#person:
##   id: 1
##   name: zhangsan
##   age: lisi
##   data: 2020/05/01
##   maps: {k1: v1,k2: v2}
##   lists:
##     - lsis
##     - zjamshan
##     - wangwu
##   dog:
##      name: 小狗
##      age: 1


server:
  port: 8888
spring:
  profiles:
    active: dev # 激活生产环境
---
# 测试环境
server:
  port: 8889
spring:
  profiles: dev
---
# 生产环境
server:
  port: 8886
spring:
  profiles: prod

